In [11]:
import numpy as np
import pandas as pd

In [12]:
import json
  
# Opening JSON file
f = open('8_a_console.json')
  
# returns JSON object as 
# a dictionary
data = json.load(f)

# Closing file
f.close()

In [13]:
times = pd.json_normalize(data)['time']

# check 851 rows
len(np.unique(times))

851

In [14]:
df = pd.json_normalize(data[0]['poses'], record_path=['keypoints'])
df.head(3)

             x           y         z     score            name
0  1025.102119  185.037017 -0.138722  0.999573            nose
1  1037.020340  167.979294 -0.115739  0.998996  left_eye_inner
2  1044.364014  169.017277 -0.115986  0.998649        left_eye

# set up for iteration

In [15]:
col_names = np.array([])

# add x
x_names = (df['name'].astype(str) + "_x").to_numpy()
# add y 
y_names = (df['name'].astype(str) + "_y").to_numpy()
# add z
z_names = (df['name'].astype(str) + "_z").to_numpy()
# add score
score_names = (df['name'].astype(str) + "_score").to_numpy()

col_names = np.append(col_names, x_names)
col_names = np.append(col_names, y_names)
col_names = np.append(col_names, z_names)
col_names = np.append(col_names, score_names)

print(len(np.unique(col_names)) == len(col_names))
print(len(col_names))

True
132

In [16]:
df_clean=pd.DataFrame(columns=col_names)
df_clean

Empty DataFrame
Columns: [nose_x, left_eye_inner_x, left_eye_x, left_eye_outer_x, right_eye_inner_x, right_eye_x, right_eye_outer_x, left_ear_x, right_ear_x, mouth_left_x, mouth_right_x, left_shoulder_x, right_shoulder_x, left_elbow_x, right_elbow_x, left_wrist_x, right_wrist_x, left_pinky_x, right_pinky_x, left_index_x, right_index_x, left_thumb_x, right_thumb_x, left_hip_x, right_hip_x, left_knee_x, right_knee_x, left_ankle_x, right_ankle_x, left_heel_x, right_heel_x, left_foot_index_x, right_foot_index_x, nose_y, left_eye_inner_y, left_eye_y, left_eye_outer_y, right_eye_inner_y, right_eye_y, right_eye_outer_y, left_ear_y, right_ear_y, mouth_left_y, mouth_right_y, left_shoulder_y, right_shoulder_y, left_elbow_y, right_elbow_y, left_wrist_y, right_wrist_y, left_pinky_y, right_pinky_y, left_index_y, right_index_y, left_thumb_y, right_thumb_y, left_hip_y, right_hip_y, left_knee_y, right_knee_y, left_ankle_y, right_ankle_y, left_heel_y, right_heel_y, left_foot_index_y, right_foot_index_y, nose_z, left_eye_inner_z, left_eye_z, left_eye_outer_z, right_eye_inner_z, right_eye_z, right_eye_outer_z, left_ear_z, right_ear_z, mouth_left_z, mouth_right_z, left_shoulder_z, right_shoulder_z, left_elbow_z, right_elbow_z, left_wrist_z, right_wrist_z, left_pinky_z, right_pinky_z, left_index_z, right_index_z, left_thumb_z, right_thumb_z, left_hip_z, right_hip_z, left_knee_z, right_knee_z, left_ankle_z, right_ankle_z, left_heel_z, right_heel_z, left_foot_index_z, right_foot_index_z, nose_score, ...]
Index: []

[0 rows x 132 columns]

# Iterate for each frame in video

In [17]:
for i in np.arange(len(data)):
    df_temp = pd.json_normalize(data[i]['poses'], record_path=['keypoints'])
    if len(df_temp)>0:
        x_values = df_temp['x'].tolist()
        y_values = df_temp['y'].tolist()
        z_values = df_temp['z'].tolist()
        score_values = df_temp['score'].tolist()

        all_values = np.append(x_values, y_values)
        all_values = np.append(all_values, z_values)
        all_values = np.append(all_values, score_values)
        len(all_values)

        df_clean.loc[i] = all_values

In [18]:
len(pd.json_normalize(data[2]['poses'], record_path=['keypoints']))

33

In [19]:
df_final = df_clean.reset_index().rename(columns={"index":'frame'})
df_final

,frame,nose_x,left_eye_inner_x,left_eye_x,left_eye_outer_x,right_eye_inner_x,right_eye_x,right_eye_outer_x,left_ear_x,right_ear_x,...,left_hip_score,right_hip_score,left_knee_score,right_knee_score,left_ankle_score,right_ankle_score,left_heel_score,right_heel_score,left_foot_index_score,right_foot_index_score
0,0,1025.102119,1037.020340,1044.364014,1051.186981,1017.173195,1009.950027,1002.074432,1062.070198,995.148125,...,0.999749,0.999412,0.321567,0.338077,0.355887,0.252753,0.147310,0.081520,0.327561,0.223377
1,1,931.785965,942.549248,950.492878,958.220558,920.287514,912.082958,904.227333,967.151413,893.518353,...,0.999769,0.999467,0.389336,0.403441,0.419357,0.326633,0.231236,0.170096,0.394467,0.299589
2,2,935.969067,946.802387,954.747047,962.372246,924.786186,916.658936,908.714333,969.843750,896.899338,...,0.999787,0.999516,0.448338,0.459856,0.474545,0.390723,0.293673,0.245080,0.452272,0.366076
3,3,933.483696,943.707447,952.591839,961.018982,923.401051,916.558971,909.362526,969.351425,896.529579,...,0.999803,0.999559,0.499472,0.506802,0.520124,0.445126,0.335248,0.303672,0.500800,0.422750
4,4,935.117397,945.304298,954.063320,962.376480,924.834309,917.815590,910.508366,970.504875,897.958775,...,0.999817,0.999599,0.548370,0.552621,0.564852,0.494493,0.385110,0.359130,0.547817,0.474965
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
841,846,911.749477,921.733360,930.002632,938.466511,899.174252,891.044140,882.896061,951.135807,874.099560,...,0.999697,0.999456,0.609135,0.595590,0.584377,0.616913,0.211013,0.228111,0.474334,0.493470
842,847,896.167889,909.145145,918.770885,928.212261,883.611031,874.526081,866.114330,946.089306,861.261921,...,0.999679,0.999486,0.591673,0.586826,0.567328,0.608573,0.202852,0.218641,0.456069,0.478029
843,848,886.084671,899.134083,908.303604,917.011242,874.233971,865.404224,857.216892,933.669033,853.024063,...,0.999661,0.999507,0.563304,0.555375,0.546408,0.576744,0.194590,0.205596,0.439289,0.450628
844,849,880.695248,893.198719,902.183361,910.408344,867.991219,858.759212,850.207100,924.611492,843.824215,...,0.999675,0.999546,0.550102,0.562986,0.549093,0.595629,0.197317,0.217900,0.446804,0.470900
845,850,877.742958,890.159168,898.246708,906.178265,865.363712,855.617924,846.348038,919.613686,838.013878,...,0.999695,0.999585,0.560603,0.586474,0.562821,0.626031,0.211809,0.248891,0.466501,0.506015

In [20]:
# used to save csv files for next steps
### DO NOT UNCOMMENT UNLESS TRYING TO CREATE NEW VERSIONS OF CSVs
# df_final.to_csv('mmla_ia_2024/soccer_ep8.csv')